const {test}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
process.env.COOKIE_SECRET=crypto.randomBytes(32).toString('base64');
const news=require('../api/news');
const session=require('../api/session');
const vault=require('../lib/session');
const google=require('../lib/google-news');
function req(method,body,cookie='',origin='https://test.example'){return{method,body,headers:{host:'test.example',origin,cookie,'content-type':'application/json'}};}
function res(){return{headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.data=JSON.parse(v);}};}
async function invoke(handler,request){const response=res();await handler(request,response);return response;}
function item(title,source,date,link){return `<item><title><![CDATA[${title} - ${source}]]></title><link>${link.replaceAll('&','&amp;')}</link><guid>id</guid><pubDate>${new Date(date).toUTCString()}</pubDate><source url="https://example.com">${source}</source></item>`;}
const now=Date.UTC(2026,8,23,12);
const feed=`<?xml version="1.0"?><rss><channel>${item('AI 반도체 투자 확대','뉴스1',now-3600000,'https://news.google.com/rss/articles/1')}${item('AI 반도체 투자 확대!','다른신문',now-7200000,'https://news.google.com/rss/articles/2')}${item('새로운 로봇 공개','연합뉴스',now-10800000,'https://news.google.com/rss/articles/3')}${item('오래된 기사','연합뉴스',now-10*86400000,'https://news.google.com/rss/articles/4')}</channel></rss>`;
test('RSS parser filters time, sorts and removes near-duplicate headlines',()=>{const result=google.parseFeed(feed,{days:3,now});assert.equal(result.fetched,3);assert.equal(result.items.length,2);assert.equal(result.items[0].title,'AI 반도체 투자 확대');assert.equal(result.items[0].publisher,'뉴스1');assert.equal(result.items[1].title,'새로운 로봇 공개');});
test('news endpoint needs no API key and returns RSS counts with zero tokens',async()=>{const current=Date.now()-3600000;const liveFeed=`<rss><channel>${item('AI 반도체 투자 확대','뉴스1',current,'https://news.google.com/rss/articles/1')}${item('AI 반도체 투자 확대!','다른신문',current-60000,'https://news.google.com/rss/articles/2')}${item('새로운 로봇 공개','연합뉴스',current-120000,'https://news.google.com/rss/articles/3')}</channel></rss>`;global.fetch=async url=>{assert.match(String(url),/news\.google\.com\/rss\/search/);assert.equal(new URL(url).searchParams.get('q'),'AI when:3d');return{ok:true,text:async()=>liveFeed};};const r=await invoke(news,req('POST',{keyword:'AI',days:3,count:20}));assert.equal(r.statusCode,200);assert.equal(r.data.provider,'google-news-rss');assert.equal(r.data.tokens,0);assert.equal(r.data.totalFetched,3);assert.equal(r.data.totalAfterDedup,2);assert.equal(r.data.items.length,2);});
test('invalid count, cross-origin request and upstream failure are handled',async()=>{let calls=0;global.fetch=async()=>{calls++;return{ok:false,status:503,text:async()=>''};};assert.equal((await invoke(news,req('POST',{keyword:'AI',days:3,count:7}))).statusCode,400);assert.equal((await invoke(news,req('POST',{keyword:'AI',days:3,count:20},'', 'https://evil.example'))).statusCode,403);assert.equal(calls,0);const failed=await invoke(news,req('POST',{keyword:'AI',days:3,count:20}));assert.equal(failed.statusCode,502);assert.match(failed.data.error,/503/);});
test('result count truncates only after deterministic deduplication',async()=>{const current=Date.now()-3600000,many=Array.from({length:25},(_,i)=>item(`서로 다른 기사 ${i}`,'매체',current-i*60000,`https://news.google.com/rss/articles/${i}`)).join('');global.fetch=async()=>({ok:true,text:async()=>`<rss><channel>${many}</channel></rss>`});const r=await invoke(news,req('POST',{keyword:'뉴스',days:3,count:20}));assert.equal(r.data.items.length,20);assert.equal(r.data.totalAfterDedup,25);assert.equal(r.data.truncated,true);});
test('legacy encrypted keys can still be deleted and tampered cookies are unreadable',async()=>{const saved=await invoke(session,req('POST',{openai:'sk-example-key-123456789',preferred:'openai'}));const cookie=saved.headers['Set-Cookie'].split(';')[0];assert.equal(vault.read(req('GET',null,cookie)).keys.openai,'sk-example-key-123456789');const value=cookie.split('=')[1],raw=Buffer.from(value,'base64url');raw[35]^=1;assert.equal(vault.read(req('GET',null,cookie.split('=')[0]+'='+raw.toString('base64url'))),null);const removed=await invoke(session,req('DELETE',null,cookie));assert.match(removed.headers['Set-Cookie'],/Max-Age=0/);});
