const {URL}=require('node:url');
class FeedError extends Error{constructor(status,message){super(message);this.status=status;}}
function decodeXml(value=''){const named={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};return value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&#(x?[0-9a-f]+);|&([a-z]+);/gi,(_,number,name)=>{if(number){const code=number[0].toLowerCase()==='x'?parseInt(number.slice(1),16):parseInt(number,10);return Number.isFinite(code)?String.fromCodePoint(code):_;}return named[name.toLowerCase()]??_;});}
function stripHtml(value=''){return decodeXml(value.replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim();}
function tag(block,name){const match=block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return match?decodeXml(match[1]).trim():'';}
function sourceTag(block){const match=block.match(/<source(?:\s[^>]*)?>([\s\S]*?)<\/source>/i);return match?stripHtml(match[1]):'';}
function cleanTitle(title,source){let value=stripHtml(title);if(source){const suffix=' - '+source;if(value.toLowerCase().endsWith(suffix.toLowerCase()))value=value.slice(0,-suffix.length).trim();}return value;}
function normalizedTitle(value){return value.normalize('NFKC').toLowerCase().replace(/\[[^\]]*\]|\([^)]*\)/g,' ').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim();}
function bigrams(value){const compact=value.replace(/\s+/g,'');const list=[];for(let i=0;i<compact.length-1;i++)list.push(compact.slice(i,i+2));return list;}
function similarity(a,b){if(a===b)return 1;if(!a||!b)return 0;const numbersA=a.match(/\d+(?:\.\d+)?/g)||[],numbersB=b.match(/\d+(?:\.\d+)?/g)||[];if(numbersA.join('|')!==numbersB.join('|'))return 0;if(Math.min(a.length,b.length)>=18&&(a.includes(b)||b.includes(a)))return .94;const left=bigrams(a),right=bigrams(b),counts=new Map();for(const gram of left)counts.set(gram,(counts.get(gram)||0)+1);let overlap=0;for(const gram of right){const count=counts.get(gram)||0;if(count){overlap++;counts.set(gram,count-1);}}return left.length+right.length?2*overlap/(left.length+right.length):0;}
function dedupe(items){const kept=[];for(const item of items){const normalized=normalizedTitle(item.title);if(!normalized)continue;if(kept.some(existing=>similarity(normalized,existing._normalized)>=.84))continue;kept.push({...item,_normalized:normalized});}return kept.map(({_normalized,...item})=>item);}
function parseFeed(xml,{days=3,now=Date.now()}={}){const cutoff=now-days*86400000,blocks=xml.match(/<item(?:\s[^>]*)?>[\s\S]*?<\/item>/gi)||[],items=[];for(const block of blocks){const publisher=sourceTag(block)||'언론사',title=cleanTitle(tag(block,'title'),publisher),link=tag(block,'link'),publishedAt=Date.parse(tag(block,'pubDate'));if(!title||!/^https:\/\//i.test(link)||!Number.isFinite(publishedAt)||publishedAt<cutoff||publishedAt>now+3600000)continue;items.push({title,publisher,date:new Date(publishedAt).toISOString(),url:link,snippet:''});}items.sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));return{fetched:items.length,items:dedupe(items)};}
async function fetchGoogleNews(keyword,days,count){const url=new URL('https://news.google.com/rss/search');url.searchParams.set('q',`${keyword} when:${days}d`);url.searchParams.set('hl','ko');url.searchParams.set('gl','KR');url.searchParams.set('ceid','KR:ko');let response;try{response=await fetch(url,{headers:{'User-Agent':'keywordnews/1.0 (+https://keywordnews.vercel.app)','Accept':'application/rss+xml, application/xml;q=0.9, text/xml;q=0.8'},signal:AbortSignal.timeout(20000)});}catch{throw new FeedError(504,'Google News RSS 연결 시간이 초과되었습니다.');}if(!response.ok)throw new FeedError(502,`Google News RSS 응답 실패 (${response.status})`);const xml=await response.text();if(xml.length>5_000_000)throw new FeedError(502,'Google News RSS 응답이 너무 큽니다.');const parsed=parseFeed(xml,{days});return{items:parsed.items.slice(0,count),totalFetched:parsed.fetched,totalAfterDedup:parsed.items.length,truncated:parsed.items.length>count,feedUrl:url.href};}
module.exports={fetchGoogleNews,parseFeed,dedupe,similarity,FeedError};
